In [13]:
#Import NumPy
import numpy as np
import time

print("NumPy version:", np.__version__)

NumPy version: 2.3.5


In [14]:
marks = np.array([
    [85, 78, 92],
    [70, 88, 76],
    [95, 91, 89],
    [65, 72, 80]
])

print("Marks Dataset:")
print(marks)

Marks Dataset:
[[85 78 92]
 [70 88 76]
 [95 91 89]
 [65 72 80]]


In [15]:
print("First Student:")
print(marks[0])

print("\nFirst Student - First Subject:")
print(marks[0, 0])

First Student:
[85 78 92]

First Student - First Subject:
85


In [16]:
print("First Two Students:")
print(marks[:2])

print("\nFirst Subject Marks:")
print(marks[:, 0])

First Two Students:
[[85 78 92]
 [70 88 76]]

First Subject Marks:
[85 70 95 65]


In [17]:
print("Total Marks:", np.sum(marks))

print("\nMarks + 5:")
print(marks + 5)

print("\nMarks * 2:")
print(marks * 2)

Total Marks: 981

Marks + 5:
[[ 90  83  97]
 [ 75  93  81]
 [100  96  94]
 [ 70  77  85]]

Marks * 2:
[[170 156 184]
 [140 176 152]
 [190 182 178]
 [130 144 160]]


In [18]:
print("Average Marks:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))
print("Standard Deviation:", np.std(marks))

Average Marks: 81.75
Highest Marks: 95
Lowest Marks: 65
Standard Deviation: 9.274741685531373


In [19]:
print("Subject-wise Average:")
print(np.mean(marks, axis=0))

print("\nStudent-wise Average:")
print(np.mean(marks, axis=1))

Subject-wise Average:
[78.75 82.25 84.25]

Student-wise Average:
[85.         78.         91.66666667 72.33333333]


In [20]:
reshaped_marks = marks.reshape(2, 6)

print("Original Shape:", marks.shape)
print("New Shape:", reshaped_marks.shape)

print("\nReshaped Array:")
print(reshaped_marks)

Original Shape: (4, 3)
New Shape: (2, 6)

Reshaped Array:
[[85 78 92 70 88 76]
 [95 91 89 65 72 80]]


In [21]:
bonus = np.array([5, 3, 2])

result = marks + bonus

print("Original Marks:")
print(marks)

print("\nBonus:")
print(bonus)

print("\nAfter Broadcasting:")
print(result)

Original Marks:
[[85 78 92]
 [70 88 76]
 [95 91 89]
 [65 72 80]]

Bonus:
[5 3 2]

After Broadcasting:
[[ 90  81  94]
 [ 75  91  78]
 [100  94  91]
 [ 70  75  82]]


In [22]:
np.save("marks.npy", marks)

print("Array saved successfully as marks.npy")

Array saved successfully as marks.npy


In [23]:
loaded_marks = np.load("marks.npy")

print("Loaded Array:")
print(loaded_marks)

Loaded Array:
[[85 78 92]
 [70 88 76]
 [95 91 89]
 [65 72 80]]


In [24]:
numbers = list(range(1000000))
numpy_numbers = np.arange(1000000)

# Python List
start = time.time()

list_result = [x * 2 for x in numbers]

list_time = time.time() - start

# NumPy
start = time.time()

numpy_result = numpy_numbers * 2

numpy_time = time.time() - start

print("Python List Time:", list_time)
print("NumPy Time:", numpy_time)

Python List Time: 0.326887845993042
NumPy Time: 0.011994600296020508


In [25]:
print("Project: NumPy Data Explorer")
print("----------------------------")
print("✓ Array Creation")
print("✓ Indexing and Slicing")
print("✓ Mathematical Operations")
print("✓ Statistical Operations")
print("✓ Axis-wise Operations")
print("✓ Reshaping")
print("✓ Broadcasting")
print("✓ Save and Load")
print("✓ Performance Comparison")


Project: NumPy Data Explorer
----------------------------
✓ Array Creation
✓ Indexing and Slicing
✓ Mathematical Operations
✓ Statistical Operations
✓ Axis-wise Operations
✓ Reshaping
✓ Broadcasting
✓ Save and Load
✓ Performance Comparison
